name: advstory
description: A complete story viewer package with lots of controls and customizations.
version: 0.1.0
homepage: https://advstory.sourcekod.com
repository: https://github.com/ertgrulll/advstory
issue_tracker: https://github.com/ertgrulll/advstory/issues
maintainer: Ertuğrul Yakın (@ertgrulll)

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  shimmer: ^2.0.0
  video_player: ^2.4.2

dev_dependencies:
  dartdoc: ^5.0.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: